# Site settings
title: Felipe Trova - Front-End
email: felipee.trova@gmail.com
url: https://felipetrova.com.br
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary: 18bc9c #80B3FF
  primary: 8cc63f #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Felipe Trova
  location: Location
  social: Siga-me!
  credits: #Credits ?

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/felipetrova
  - title: facebook
    url: https://www.facebook.com/ftweb
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/felipe_trova
  - title: github
    url: http://github.com/felipetrova

# Postal address (add as many lines as necessary)
address:
  - line: Indaiatuba
  - line: SP-Brasil

# Credits content
credits: 'Feito com <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> e <span class="love">❤</span></p>'

# Build settings
markdown: kramdown
permalink: pretty
