
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            America/Sao_Paulo # eg. Asia/Kathmandu
locale:              pt_br # eg. en_us
name:				         Felipe Trova
title:               Felipe Trova - Front-End Developer
tagline:             'tagline'
description:         'Felipe Trova - Front-End Developer. Projetos e posts sobre HTML(5), CSS(3), JS, Git, Pré-processadores, Tasks Runners e outras tecnologias'
url:                 http://felipetrova.github.io/
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                '/assets/img/icon.png' # /assets/img/icon.png [best 300px X 300px]
disqus:              felipetrova # get it on https://disqus.com/admin/

author:
  name:           	 Felipe Trova
  url:            	 http://felipetrova.github.io/
  facebook:          ftweb
  twitter:           felipetrova
  google_plus:       felipetrova
  linkedin:          felipetrova
  dribbble:          felipetrova
  pinterest:         
  kiva:              

fb_admins:           felipetrova
fb_appid:            1617829778476979

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
